/** @file
 *  @brief MAVLink comm protocol generated from merivus_ftc.xml
 *  @see http://mavlink.org
 */
#pragma once
#ifndef MAVLINK_MERIVUS_FTC_H
#define MAVLINK_MERIVUS_FTC_H

#ifndef MAVLINK_H
    #error Wrong include order: MAVLINK_MERIVUS_FTC.H MUST NOT BE DIRECTLY USED. Include mavlink.h from the same directory instead or set ALL AND EVERY defines from MAVLINK.H manually accordingly, including the #define MAVLINK_H call.
#endif

#define MAVLINK_MERIVUS_FTC_XML_HASH 822722633601455063

#ifdef __cplusplus
extern "C" {
#endif

// MESSAGE LENGTHS AND CRCS

#ifndef MAVLINK_MESSAGE_LENGTHS
#define MAVLINK_MESSAGE_LENGTHS {}
#endif

#ifndef MAVLINK_MESSAGE_CRCS
#define MAVLINK_MESSAGE_CRCS {{60000, 29, 78, 153, 0, 0, 0}, {60001, 153, 24, 78, 0, 0, 0}, {60002, 136, 38, 38, 0, 0, 0}, {60003, 5, 65, 117, 0, 0, 0}}
#endif

#include "../protocol.h"

#define MAVLINK_ENABLED_MERIVUS_FTC

// ENUM DEFINITIONS


/** @brief Aggregated MERIVUS fault-tolerant-control subsystem state. */
#ifndef HAVE_ENUM_MERIVUS_FTC_SYSTEM_STATE
#define HAVE_ENUM_MERIVUS_FTC_SYSTEM_STATE
typedef enum MERIVUS_FTC_SYSTEM_STATE
{
   MERIVUS_FTC_SYSTEM_STATE_DISABLED=0, /*  | */
   MERIVUS_FTC_SYSTEM_STATE_NORMAL=1, /*  | */
   MERIVUS_FTC_SYSTEM_STATE_DEGRADED=2, /*  | */
   MERIVUS_FTC_SYSTEM_STATE_FAULT_CONFIRMED=3, /*  | */
   MERIVUS_FTC_SYSTEM_STATE_RECOVERY_READY=4, /*  | */
   MERIVUS_FTC_SYSTEM_STATE_RECOVERY_ACTIVE=5, /*  | */
   MERIVUS_FTC_SYSTEM_STATE_EMERGENCY_LAND=6, /*  | */
   MERIVUS_FTC_SYSTEM_STATE_FAILED=7, /*  | */
   MERIVUS_FTC_SYSTEM_STATE_INITIALIZING=8, /*  | */
   MERIVUS_FTC_SYSTEM_STATE_CALIBRATING=9, /*  | */
   MERIVUS_FTC_SYSTEM_STATE_READY=10, /*  | */
   MERIVUS_FTC_SYSTEM_STATE_UNOBSERVABLE=11, /*  | */
   MERIVUS_FTC_SYSTEM_STATE_SHADOW=12, /*  | */
   MERIVUS_FTC_SYSTEM_STATE_RECOVERY_CANDIDATE=13, /*  | */
   MERIVUS_FTC_SYSTEM_STATE_ACTIVE_ALLOCATION=14, /*  | */
   MERIVUS_FTC_SYSTEM_STATE_ENUM_END=15, /*  | */
} MERIVUS_FTC_SYSTEM_STATE;
#endif

/** @brief Motor-health observer state. */
#ifndef HAVE_ENUM_MERIVUS_FTC_MONITOR_STATE
#define HAVE_ENUM_MERIVUS_FTC_MONITOR_STATE
typedef enum MERIVUS_FTC_MONITOR_STATE
{
   MERIVUS_FTC_MONITOR_STATE_DISABLED=0, /*  | */
   MERIVUS_FTC_MONITOR_STATE_CALIBRATING=1, /*  | */
   MERIVUS_FTC_MONITOR_STATE_VALID=2, /*  | */
   MERIVUS_FTC_MONITOR_STATE_INVALID=3, /*  | */
   MERIVUS_FTC_MONITOR_STATE_ENUM_END=4, /*  | */
} MERIVUS_FTC_MONITOR_STATE;
#endif

/** @brief Observed propulsion fault classification. This is a diagnostic classification, not proof of component lifetime. */
#ifndef HAVE_ENUM_MERIVUS_FTC_FAULT_TYPE
#define HAVE_ENUM_MERIVUS_FTC_FAULT_TYPE
typedef enum MERIVUS_FTC_FAULT_TYPE
{
   MERIVUS_FTC_FAULT_NONE=0, /*  | */
   MERIVUS_FTC_FAULT_UNKNOWN_PROPULSION_DEGRADATION=1, /*  | */
   MERIVUS_FTC_FAULT_PROP_DAMAGE=2, /*  | */
   MERIVUS_FTC_FAULT_MOTOR_DEGRADATION=3, /*  | */
   MERIVUS_FTC_FAULT_MOTOR_STOP=4, /*  | */
   MERIVUS_FTC_FAULT_ESC_OR_POWER_FAILURE=5, /*  | */
   MERIVUS_FTC_FAULT_INTERMITTENT_PROPULSION_FAILURE=6, /*  | */
   MERIVUS_FTC_FAULT_MECHANICAL_IMBALANCE=7, /*  | */
   MERIVUS_FTC_FAULT_EXTERNAL_DISTURBANCE=8, /*  | */
   MERIVUS_FTC_FAULT_MODEL_MISMATCH=9, /*  | */
   MERIVUS_FTC_FAULT_TYPE_ENUM_END=10, /*  | */
} MERIVUS_FTC_FAULT_TYPE;
#endif

/** @brief Remaining control-authority classification. */
#ifndef HAVE_ENUM_MERIVUS_FTC_AUTHORITY_STATE
#define HAVE_ENUM_MERIVUS_FTC_AUTHORITY_STATE
typedef enum MERIVUS_FTC_AUTHORITY_STATE
{
   MERIVUS_FTC_AUTHORITY_STATE_FULL_CONTROL=0, /*  | */
   MERIVUS_FTC_AUTHORITY_STATE_DEGRADED_CONTROL=1, /*  | */
   MERIVUS_FTC_AUTHORITY_STATE_YAW_UNCONTROLLABLE=2, /*  | */
   MERIVUS_FTC_AUTHORITY_STATE_ATTITUDE_DEGRADED=3, /*  | */
   MERIVUS_FTC_AUTHORITY_STATE_THRUST_INSUFFICIENT=4, /*  | */
   MERIVUS_FTC_AUTHORITY_STATE_RECOVERY_ONLY=5, /*  | */
   MERIVUS_FTC_AUTHORITY_STATE_UNCONTROLLABLE=6, /*  | */
   MERIVUS_FTC_AUTHORITY_STATE_ENUM_END=7, /*  | */
} MERIVUS_FTC_AUTHORITY_STATE;
#endif

/** @brief Highest FTC integration stage currently represented by the data path. ACTIVE requires an explicitly connected actuator command path. */
#ifndef HAVE_ENUM_MERIVUS_FTC_CONTROL_MODE
#define HAVE_ENUM_MERIVUS_FTC_CONTROL_MODE
typedef enum MERIVUS_FTC_CONTROL_MODE
{
   MERIVUS_FTC_CONTROL_MODE_DISABLED=0, /*  | */
   MERIVUS_FTC_CONTROL_MODE_OBSERVE=1, /*  | */
   MERIVUS_FTC_CONTROL_MODE_SHADOW=2, /*  | */
   MERIVUS_FTC_CONTROL_MODE_CANDIDATE=3, /*  | */
   MERIVUS_FTC_CONTROL_MODE_ACTIVE=4, /*  | */
   MERIVUS_FTC_CONTROL_MODE_ENUM_END=5, /*  | */
} MERIVUS_FTC_CONTROL_MODE;
#endif

/** @brief Observed impact classification. */
#ifndef HAVE_ENUM_MERIVUS_FTC_IMPACT_TYPE
#define HAVE_ENUM_MERIVUS_FTC_IMPACT_TYPE
typedef enum MERIVUS_FTC_IMPACT_TYPE
{
   MERIVUS_FTC_IMPACT_TYPE_NONE=0, /*  | */
   MERIVUS_FTC_IMPACT_TYPE_EXTERNAL=1, /*  | */
   MERIVUS_FTC_IMPACT_TYPE_HARD_LANDING=2, /*  | */
   MERIVUS_FTC_IMPACT_TYPE_ENUM_END=3, /*  | */
} MERIVUS_FTC_IMPACT_TYPE;
#endif

/** @brief Observed loss-of-control state. */
#ifndef HAVE_ENUM_MERIVUS_FTC_LOC_STATE
#define HAVE_ENUM_MERIVUS_FTC_LOC_STATE
typedef enum MERIVUS_FTC_LOC_STATE
{
   MERIVUS_FTC_LOC_STATE_NORMAL=0, /*  | */
   MERIVUS_FTC_LOC_STATE_DISTURBED=1, /*  | */
   MERIVUS_FTC_LOC_STATE_RECOVERY_RECOMMENDED=2, /*  | */
   MERIVUS_FTC_LOC_STATE_LOSS_OF_CONTROL=3, /*  | */
   MERIVUS_FTC_LOC_STATE_UNRECOVERABLE=4, /*  | */
   MERIVUS_FTC_LOC_STATE_ENUM_END=5, /*  | */
} MERIVUS_FTC_LOC_STATE;
#endif

/** @brief Disconnected recovery-candidate state machine state. */
#ifndef HAVE_ENUM_MERIVUS_FTC_RECOVERY_STATE
#define HAVE_ENUM_MERIVUS_FTC_RECOVERY_STATE
typedef enum MERIVUS_FTC_RECOVERY_STATE
{
   MERIVUS_FTC_RECOVERY_STATE_DISABLED=0, /*  | */
   MERIVUS_FTC_RECOVERY_STATE_MONITORING=1, /*  | */
   MERIVUS_FTC_RECOVERY_STATE_DISTURBANCE_DETECTED=2, /*  | */
   MERIVUS_FTC_RECOVERY_STATE_RATE_DAMPING=3, /*  | */
   MERIVUS_FTC_RECOVERY_STATE_THRUST_VECTOR_RECOVERY=4, /*  | */
   MERIVUS_FTC_RECOVERY_STATE_ATTITUDE_RECOVERY=5, /*  | */
   MERIVUS_FTC_RECOVERY_STATE_ALTITUDE_STABILIZATION=6, /*  | */
   MERIVUS_FTC_RECOVERY_STATE_CONTROL_REENTRY=7, /*  | */
   MERIVUS_FTC_RECOVERY_STATE_EMERGENCY_LAND=8, /*  | */
   MERIVUS_FTC_RECOVERY_STATE_ABORTED=9, /*  | */
   MERIVUS_FTC_RECOVERY_STATE_FAILED=10, /*  | */
   MERIVUS_FTC_RECOVERY_STATE_VERTICAL_SPEED_RECOVERY=11, /*  | */
   MERIVUS_FTC_RECOVERY_STATE_ENUM_END=12, /*  | */
} MERIVUS_FTC_RECOVERY_STATE;
#endif

/** @brief Validity and source flags for MERIVUS_FTC_MOTOR_STATUS. */
#ifndef HAVE_ENUM_MERIVUS_FTC_MOTOR_FLAGS
#define HAVE_ENUM_MERIVUS_FTC_MOTOR_FLAGS
typedef enum MERIVUS_FTC_MOTOR_FLAGS
{
   MERIVUS_FTC_MOTOR_FLAGS_MONITOR_ENABLED=1, /*  | */
   MERIVUS_FTC_MOTOR_FLAGS_MODEL_VALID=2, /*  | */
   MERIVUS_FTC_MOTOR_FLAGS_ESC_DATA_AVAILABLE=4, /*  | */
   MERIVUS_FTC_MOTOR_FLAGS_IMU_ONLY=8, /*  | */
   MERIVUS_FTC_MOTOR_FLAGS_ENUM_END=9, /*  | */
} MERIVUS_FTC_MOTOR_FLAGS;
#endif

/** @brief Validity and integration flags for MERIVUS_FTC_CONTROL_STATUS. */
#ifndef HAVE_ENUM_MERIVUS_FTC_CONTROL_FLAGS
#define HAVE_ENUM_MERIVUS_FTC_CONTROL_FLAGS
typedef enum MERIVUS_FTC_CONTROL_FLAGS
{
   MERIVUS_FTC_CONTROL_FLAGS_MONITOR_ENABLED=1, /*  | */
   MERIVUS_FTC_CONTROL_FLAGS_AUTHORITY_VALID=2, /*  | */
   MERIVUS_FTC_CONTROL_FLAGS_MATRIX_VALID=4, /*  | */
   MERIVUS_FTC_CONTROL_FLAGS_SHADOW_VALID=8, /*  | */
   MERIVUS_FTC_CONTROL_FLAGS_YAW_SACRIFICED=16, /*  | */
   MERIVUS_FTC_CONTROL_FLAGS_RECOVERY_ELIGIBLE=32, /*  | */
   MERIVUS_FTC_CONTROL_FLAGS_RECOVERY_CANDIDATE_VALID=64, /*  | */
   MERIVUS_FTC_CONTROL_FLAGS_ACTIVE_COMMAND_PATH=128, /*  | */
   MERIVUS_FTC_CONTROL_FLAGS_ENUM_END=129, /*  | */
} MERIVUS_FTC_CONTROL_FLAGS;
#endif

/** @brief Validity and event flags for MERIVUS_FTC_EXTREME_STATUS. */
#ifndef HAVE_ENUM_MERIVUS_FTC_EXTREME_FLAGS
#define HAVE_ENUM_MERIVUS_FTC_EXTREME_FLAGS
typedef enum MERIVUS_FTC_EXTREME_FLAGS
{
   MERIVUS_FTC_EXTREME_FLAGS_VALID=1, /*  | */
   MERIVUS_FTC_EXTREME_FLAGS_IMPACT_DETECTED=2, /*  | */
   MERIVUS_FTC_EXTREME_FLAGS_HARD_LANDING=4, /*  | */
   MERIVUS_FTC_EXTREME_FLAGS_RECOVERY_ELIGIBLE=8, /*  | */
   MERIVUS_FTC_EXTREME_FLAGS_INTERVENTION_ENABLED=16, /*  | */
   MERIVUS_FTC_EXTREME_FLAGS_RECOVERY_CANDIDATE_VALID=32, /*  | */
   MERIVUS_FTC_EXTREME_FLAGS_RECOVERY_STATE_ACTIVE=64, /*  | */
   MERIVUS_FTC_EXTREME_FLAGS_ENUM_END=65, /*  | */
} MERIVUS_FTC_EXTREME_FLAGS;
#endif

/** @brief Validity and SITL injection flags for MERIVUS_FTC_DIAGNOSTICS. */
#ifndef HAVE_ENUM_MERIVUS_FTC_DIAGNOSTIC_FLAGS
#define HAVE_ENUM_MERIVUS_FTC_DIAGNOSTIC_FLAGS
typedef enum MERIVUS_FTC_DIAGNOSTIC_FLAGS
{
   MERIVUS_FTC_DIAGNOSTIC_FLAGS_MODEL_VALID=1, /*  | */
   MERIVUS_FTC_DIAGNOSTIC_FLAGS_SHADOW_VALID=2, /*  | */
   MERIVUS_FTC_DIAGNOSTIC_FLAGS_EXTREME_VALID=4, /*  | */
   MERIVUS_FTC_DIAGNOSTIC_FLAGS_SIMULATION_ENABLED=8, /*  | */
   MERIVUS_FTC_DIAGNOSTIC_FLAGS_SIMULATION_INTERMITTENT=16, /*  | */
   MERIVUS_FTC_DIAGNOSTIC_FLAGS_ENUM_END=17, /*  | */
} MERIVUS_FTC_DIAGNOSTIC_FLAGS;
#endif

// MAVLINK VERSION

#ifndef MAVLINK_VERSION
#define MAVLINK_VERSION 3
#endif

#if (MAVLINK_VERSION == 0)
#undef MAVLINK_VERSION
#define MAVLINK_VERSION 3
#endif

// MESSAGE DEFINITIONS
#include "./mavlink_msg_merivus_ftc_motor_status.h"
#include "./mavlink_msg_merivus_ftc_control_status.h"
#include "./mavlink_msg_merivus_ftc_extreme_status.h"
#include "./mavlink_msg_merivus_ftc_diagnostics.h"

// base include



#if MAVLINK_MERIVUS_FTC_XML_HASH == MAVLINK_PRIMARY_XML_HASH
# define MAVLINK_MESSAGE_INFO {MAVLINK_MESSAGE_INFO_MERIVUS_FTC_MOTOR_STATUS, MAVLINK_MESSAGE_INFO_MERIVUS_FTC_CONTROL_STATUS, MAVLINK_MESSAGE_INFO_MERIVUS_FTC_EXTREME_STATUS, MAVLINK_MESSAGE_INFO_MERIVUS_FTC_DIAGNOSTICS}
# define MAVLINK_MESSAGE_NAMES {{ "MERIVUS_FTC_CONTROL_STATUS", 60001 }, { "MERIVUS_FTC_DIAGNOSTICS", 60003 }, { "MERIVUS_FTC_EXTREME_STATUS", 60002 }, { "MERIVUS_FTC_MOTOR_STATUS", 60000 }}
# if MAVLINK_COMMAND_24BIT
#  include "../mavlink_get_info.h"
# endif
#endif

#ifdef __cplusplus
}
#endif // __cplusplus
#endif // MAVLINK_MERIVUS_FTC_H
